### ISSUE TITLE
trepanjs does not seem to respect 'Current directory'

### ISSUE THREAD

**Issue by bdirito** [rocky/trepanjs#3]
```
Current directory: ~/dev/locution/responder
Command: trepanjs c:/Users/bdirito/dev/locution/responder/node_modules/protractor/bin/protractor ./protractor.conf.js
(trepanjs) Debugger listening on [::]:5858
(trepanjs) connecting to port 5858... ok
(trepanjs) break in c:\Users\bdirito\dev\locution\responder\node_modules\protractor\bin\protractor at line 3:1
   2  
-> 3 process.env.NODE_ENV = process.env.NODE_ENV || 'test';
   4  
(trepanjs) c
(trepanjs) (trepanjs) [10:44:38] E/configParser - Error code: 105
(trepanjs) [10:44:38] E/configParser - Error message: failed loading configuration file ./protractor.conf.js
(trepanjs) [10:44:38] E/configParser - Error: Cannot find module 'c:\Users\bdirito\dev\locution\protractor.conf.js'
```

Notice current directory is listed as `~/dev/locution/responder` and there exists a `~/dev/locution/responder/protractor.conf.js` file

however when it comes time to load the config file we looked in `~/dev/locution/protractor.conf.js` - notably the `/responder` part of the current directory has been dropped.

**Comment by rocky** [comment]
Does this behavior also happen when you use `node debug` instead of `trepanjs`?

**Comment by bdirito** [comment]
Im sorry - it looks like this behavior only happens inside emacs. Still cant get it to _work_ but im not necessarily convinced its a trepanjs issue anymore. Closing ticket.
